import { FieldDefinition, FieldGroup, StudentRecord } from "./types";

export const SCHEMA_FIELDS: FieldDefinition[] = [
  { index: 1, column: "A", label: "STT", key: "stt" },
  { index: 2, column: "B", label: "Mã học sinh", key: "maHocSinh" },
  { index: 3, column: "C", label: "Mã VEMIS", key: "maVemis" },
  { index: 4, column: "D", label: "Mã MOET", key: "maMoet" },
  { index: 5, column: "E", label: "Sổ đăng bộ", key: "soDangBo" },
  { index: 6, column: "F", label: "Họ và tên", key: "hoVaTen" },
  { index: 7, column: "G", label: "Ngày sinh", key: "ngaySinh" },
  { index: 8, column: "H", label: "Ngày vào trường", key: "ngayVaoTruong" },
  { index: 9, column: "I", label: "Giới tính", key: "gioiTinh" },
  { index: 10, column: "J", label: "Quốc tịch", key: "quocTich" },
  { index: 11, column: "K", label: "Chỗ ở hiện nay - SN/Xóm", key: "choO_SNXom" },
  { index: 12, column: "L", label: "Chỗ ở hiện nay - Khu dân cư", key: "choO_KhuDanCu" },
  { index: 13, column: "M", label: "Chỗ ở hiện nay - Xã/Phường", key: "choO_XaPhuong" },
  { index: 14, column: "N", label: "Chỗ ở hiện nay - Tỉnh/Tp", key: "choO_TinhTp" },
  { index: 15, column: "O", label: "Hộ khẩu thường trú - SN/Xóm", key: "hokhau_SNXom" },
  { index: 16, column: "P", label: "Hộ khẩu thường trú - Khu dân cư", key: "hokhau_KhuDanCu" },
  { index: 17, column: "Q", label: "Hộ khẩu thường trú - Xã/Phường", key: "hokhau_XaPhuong" },
  { index: 18, column: "R", label: "Hộ khẩu thường trú - Tỉnh/Tp", key: "hokhau_TinhTp" },
  { index: 19, column: "S", label: "Nơi sinh - Thông tin nơi sinh", key: "noiSinh_ThongTin" },
  { index: 20, column: "T", label: "Nơi sinh - Xã/Phường", key: "noiSinh_XaPhuong" },
  { index: 21, column: "U", label: "Nơi sinh - Tỉnh/Tp", key: "noiSinh_TinhTp" },
  { index: 22, column: "V", label: "Quê quán - Thông tin quê quán", key: "queQuan_ThongTin" },
  { index: 23, column: "W", label: "Quê quán - Xã/Phường", key: "queQuan_XaPhuong" },
  { index: 24, column: "X", label: "Quê quán - Tỉnh/Tp", key: "queQuan_TinhTp" },
  { index: 25, column: "Y", label: "Nơi khai sinh - Xã/Phường", key: "noiKhaiSinh_XaPhuong" },
  { index: 26, column: "Z", label: "Nơi khai sinh - Tỉnh/Tp", key: "noiKhaiSinh_TinhTp" },
  { index: 27, column: "AA", label: "Căn cước", key: "canCuoc" },
  { index: 28, column: "AB", label: "Ngày cấp Căn cước", key: "ngayCapCanCuoc" },
  { index: 29, column: "AC", label: "Nơi cấp Căn cước", key: "noiCapCanCuoc" },
  { index: 30, column: "AD", label: "Dân tộc", key: "danToc" },
  { index: 31, column: "AE", label: "Tôn giáo", key: "tonGiao" },
  { index: 32, column: "AF", label: "Diện chính sách", key: "dienChinhSach" },
  { index: 33, column: "AG", label: "Cận nghèo", key: "canNgheo" },
  { index: 34, column: "AH", label: "Đoàn viên", key: "doanVien" },
  { index: 35, column: "AI", label: "Đội viên", key: "doiVien" },
  { index: 36, column: "AJ", label: "Tên cha", key: "tenCha" },
  { index: 37, column: "AK", label: "Nghề nghiệp cha", key: "ngheNghiepCha" },
  { index: 38, column: "AL", label: "Năm sinh cha", key: "namSinhCha" },
  { index: 39, column: "AM", label: "Tên mẹ", key: "tenMe" },
  { index: 40, column: "AN", label: "Nghề nghiệp mẹ", key: "ngheNghiepMe" },
  { index: 41, column: "AO", label: "Năm sinh mẹ", key: "namSinhMe" },
  { index: 42, column: "AP", label: "Điện thoại SLL", key: "dienThoaiSLL" },
  { index: 43, column: "AQ", label: "Email SLL", key: "emailSLL" },
  { index: 44, column: "AR", label: "Điện thoại bố", key: "dienThoaiBo" },
  { index: 45, column: "AS", label: "Điện thoại mẹ", key: "dienThoaiMe" },
  { index: 46, column: "AT", label: "Điện thoại HS", key: "dienThoaiHS" },
  { index: 47, column: "AU", label: "Khuyết tật", key: "khuyetTat" },
  { index: 48, column: "AV", label: "N.trú, B.trú", key: "ntruBtru" },
  { index: 49, column: "AW", label: "Ghi chú", key: "ghiChu" },
];

export function groupStudentFields(student: StudentRecord): FieldGroup[] {
  return [
    {
      id: "thong_tin_co_ban",
      title: "1. Thông tin cơ bản",
      icon: "👤",
      fields: [
        { label: "STT", value: student.stt },
        { label: "Họ và tên", value: student.hoVaTen },
        { label: "Ngày sinh", value: student.ngaySinh },
        { label: "Giới tính", value: student.gioiTinh },
        { label: "Mã học sinh", value: student.maHocSinh },
        { label: "Mã VEMIS", value: student.maVemis },
        { label: "Mã MOET", value: student.maMoet },
        { label: "Sổ đăng bộ", value: student.soDangBo },
        { label: "Ngày vào trường", value: student.ngayVaoTruong },
        { label: "Quốc tịch", value: student.quocTich },
      ],
    },
    {
      id: "cho_o_hien_nay",
      title: "2. Chỗ ở hiện nay",
      icon: "🏠",
      fields: [
        { label: "SN/Xóm", value: student.choO_SNXom },
        { label: "Khu dân cư", value: student.choO_KhuDanCu },
        { label: "Xã/Phường", value: student.choO_XaPhuong },
        { label: "Tỉnh/Tp", value: student.choO_TinhTp },
      ],
    },
    {
      id: "ho_khau_thuong_tru",
      title: "3. Hộ khẩu thường trú",
      icon: "📑",
      fields: [
        { label: "SN/Xóm", value: student.hokhau_SNXom },
        { label: "Khu dân cư", value: student.hokhau_KhuDanCu },
        { label: "Xã/Phường", value: student.hokhau_XaPhuong },
        { label: "Tỉnh/Tp", value: student.hokhau_TinhTp },
      ],
    },
    {
      id: "noi_sinh_que_quan",
      title: "4. Nơi sinh – Quê quán – Khai sinh",
      icon: "📍",
      fields: [
        { label: "Nơi sinh - Thông tin", value: student.noiSinh_ThongTin },
        { label: "Nơi sinh - Xã/Phường", value: student.noiSinh_XaPhuong },
        { label: "Nơi sinh - Tỉnh/Tp", value: student.noiSinh_TinhTp },
        { label: "Quê quán - Thông tin", value: student.queQuan_ThongTin },
        { label: "Quê quán - Xã/Phường", value: student.queQuan_XaPhuong },
        { label: "Quê quán - Tỉnh/Tp", value: student.queQuan_TinhTp },
        { label: "Nơi khai sinh - Xã/Phường", value: student.noiKhaiSinh_XaPhuong },
        { label: "Nơi khai sinh - Tỉnh/Tp", value: student.noiKhaiSinh_TinhTp },
      ],
    },
    {
      id: "can_cuoc",
      title: "5. Căn cước công dân",
      icon: "🪪",
      fields: [
        { label: "Căn cước", value: student.canCuoc },
        { label: "Ngày cấp Căn cước", value: student.ngayCapCanCuoc },
        { label: "Nơi cấp Căn cước", value: student.noiCapCanCuoc },
      ],
    },
    {
      id: "dan_toc_chinh_sach",
      title: "6. Dân tộc – Tôn giáo – Chính sách",
      icon: "⭐",
      fields: [
        { label: "Dân tộc", value: student.danToc },
        { label: "Tôn giáo", value: student.tonGiao },
        { label: "Diện chính sách", value: student.dienChinhSach },
        { label: "Cận nghèo", value: student.canNgheo },
        { label: "Đoàn viên", value: student.doanVien },
        { label: "Đội viên", value: student.doiVien },
      ],
    },
    {
      id: "cha_me",
      title: "7. Thông tin cha mẹ",
      icon: "👨‍👩‍👦",
      fields: [
        { label: "Tên cha", value: student.tenCha },
        { label: "Nghề nghiệp cha", value: student.ngheNghiepCha },
        { label: "Năm sinh cha", value: student.namSinhCha },
        { label: "Tên mẹ", value: student.tenMe },
        { label: "Nghề nghiệp mẹ", value: student.ngheNghiepMe },
        { label: "Năm sinh mẹ", value: student.namSinhMe },
      ],
    },
    {
      id: "lien_he",
      title: "8. Thông tin liên hệ",
      icon: "📞",
      fields: [
        { label: "Điện thoại SLL", value: student.dienThoaiSLL },
        { label: "Email SLL", value: student.emailSLL },
        { label: "Điện thoại bố", value: student.dienThoaiBo },
        { label: "Điện thoại mẹ", value: student.dienThoaiMe },
        { label: "Điện thoại HS", value: student.dienThoaiHS },
      ],
    },
    {
      id: "khuyet_tat_ghi_chu",
      title: "9. Khuyết tật – Bán trú – Ghi chú",
      icon: "📝",
      fields: [
        { label: "Khuyết tật", value: student.khuyetTat },
        { label: "N.trú, B.trú", value: student.ntruBtru },
        { label: "Ghi chú", value: student.ghiChu },
      ],
    },
  ];
}
